version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  products-service:
    build: ./products-service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - auth-service

  orders-service:
    build: ./orders-service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - auth-service
      - products-service