version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: always
    networks:
      - payetonkawa-net

  mongo:
    image: mongo
    container_name: auth-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
        - payetonkawa-net

  postgres:
    image: postgres:15
    container_name: product-postgres
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - payetonkawa-net

  postgres-orders:
    image: postgres:15
    container_name: orders-postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres-orders-data:/var/lib/postgresql/data
    restart: always
    networks:
      - payetonkawa-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=auth-mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/auth-db
    depends_on:
      - mongo
    restart: always
    networks:
      - payetonkawa-net

  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - MONGO_URI=mongodb://mongo:27017/auth-db
      - JWT_SECRET=T2iZo5KGASNOTq3zXSH31WHmnFbs7FLEVJddt54h
    restart: always
    networks:
      - payetonkawa-net

  products-service:
    build: ./product-service
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - auth-service
      - postgres
    restart: always
    networks:
      - payetonkawa-net

  orders-service:
    build: ./commande-service
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    depends_on:
      - rabbitmq
      - auth-service
      - products-service
      - postgres-orders
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_pass
      POSTGRES_HOST: postgres-orders
      POSTGRES_PORT: 5433
    restart: always
    networks:
      - payetonkawa-net

volumes:
  rabbitmq-data:
  mongo-data:
  postgres-data:
  postgres-orders-data:


networks:
  payetonkawa-net:
    driver: bridge