global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']

  - job_name: 'products-service'
    static_configs:
      - targets: ['products-service:8000']

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:8002']
